export let dataForPassengerTickets = [
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '1',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '2',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '3',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '4',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '5',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    branchNumber: '1',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    branchPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    typeOfDocument: 'Carnet Identidad',
    identificationNumber: '7896541',
    seatId: '6',
    typeOfSeat: 'Semi-cama',
    seatPrice: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
];
