export let dataForPassengerTickets = [
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '1',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '2',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '3',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '4',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '5',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  {
    companyName: 'Sin Fronteras',
    ticketNumber: '123456789',
    issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
    companyPhone: '46410523',
    origin: 'Sucre',
    destiny: 'Santa Cruz',
    travelDate: '30/5/2022',
    DepartureTime: '20:30',
    lane: '0', //carril
    passengerName: 'Santillan Quispe Javier Angel',
    identificationNumber: '7896541',
    seat: '6',
    typeOfSeat: 'Semi-cama',
    price: '30',
    legend: 'Gracias por su compra, le deseamos un buen viaje.',
  },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '7',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '8',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '9',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '10',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '11',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
  // {
  //   companyName: 'Sin Fronteras',
  //   ticketNumber: '123456789',
  //   issuingUser: 'Santillan Reyna Ariel Angel', //usuario emisor
  //   companyPhone: '46410523',
  //   origin: 'Sucre',
  //   destiny: 'Santa Cruz',
  //   travelDate: '30/5/2022',
  //   DepartureTime: '20:30',
  //   lane: '0', //carril
  //   passengerName: 'Santillan Quispe Javier Angel',
  //   identificationNumber: '7896541',
  //   seat: '12',
  //   typeOfSeat: 'Semi-cama',
  //   price: '30',
  //   legend: 'Gracias por su compra, le deseamos un buen viaje.',
  // },
];
